# Generated by Django 3.0.8 on 2020-07-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullCycle', '0002_auto_20200704_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aulas',
            new_name='Aula',
        ),
    ]
